// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD6voFvvsF2h4gP9Ahw8u2cRVP2J1v_Y0',
    appId: '1:434927365555:web:abdea421ea9857a9302fc6',
    messagingSenderId: '434927365555',
    projectId: 'varta-app-effc9',
    authDomain: 'varta-app-effc9.firebaseapp.com',
    storageBucket: 'varta-app-effc9.appspot.com',
    measurementId: 'G-3YMG1V7ST9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV3qlqTwDENRe_-bfcF5Qj-KwzkrJpF0A',
    appId: '1:434927365555:android:a0dfde3edc76e07b302fc6',
    messagingSenderId: '434927365555',
    projectId: 'varta-app-effc9',
    storageBucket: 'varta-app-effc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx_umTivM2KkELIbxSUx_EdPw9-8hsoc4',
    appId: '1:434927365555:ios:729e64aa4818567a302fc6',
    messagingSenderId: '434927365555',
    projectId: 'varta-app-effc9',
    storageBucket: 'varta-app-effc9.appspot.com',
    iosBundleId: 'com.example.vartaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx_umTivM2KkELIbxSUx_EdPw9-8hsoc4',
    appId: '1:434927365555:ios:03a4ee1bcaa6598c302fc6',
    messagingSenderId: '434927365555',
    projectId: 'varta-app-effc9',
    storageBucket: 'varta-app-effc9.appspot.com',
    iosBundleId: 'com.example.vartaApp.RunnerTests',
  );
}
